version: '3'
services:
  mysql:
    image: mysql_db
    container_name: patient_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mediscreen"
      MYSQL_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
    volumes:
      - mysql-data:/data/db
    ports:
      - "33061:3306"

  mongodb:
    image: mongo:5
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  diagnostic :
    image: diagnostic
    container_name: diagnosticappcontainer
    environment:
      PATIENT_URL: http://patient:8081
      HISTORY_URL: http://history:8082
      MEDISCREEN_URL: http://mediscreen:8080
    ports:
      - "8083:8083"

  history :
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_DATABASE: PatientNote
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: root
      MEDISCREEN_URL: http://mediscreen:8080
    image: history
    container_name: historyappcontainer
    ports:
      - "8082:8082"

  patient :
    depends_on:
      - mysql
    environment:
      DIAGNOSTIC_URL: http://diagnostic:8083
      MEDISCREEN_URL: http://mediscreen:8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mediscreen
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    image: patient
    container_name: patientappcontainer
    ports:
      - "8081:8081"

  mediscreen:
    depends_on:
      - patient
      - history
      - diagnostic
    restart: always
    image: mediscreen
    environment:
      PATIENT_URL: http://patient:8081
      HISTORY_URL: http://history:8082
      DIAGNOSTIC_URL: http://diagnostic:8083
    ports:
      - "8080:8080"

volumes:
  mysql-data:
  mongo-data:


